<?php

/**
 * 权限描述
 */
return [
    
   //  'api.auth'=>[
        'api.auth' => '用户权限',
        'api.auth.login' => '用户登录',
        'api.auth.logout' => '用户退出',
        'api.auth.refresh' => '用户刷新',
        'api.auth.getUserInfo' => '用户信息',
        'api.auth.saveUserInfo' => '更新用户',
        'api.auth.modifyPassword' => '修改密码',
   // ],
    
   // 'api.users'=>[
        'api.users' => '用户',
        'api.users.index' => '用户列表',
        'api.users.create' => '创建用户',
        'api.users.store' => '保存用户',
        'api.users.show' => '显示用户',
        'api.users.edit' => '编辑用户',
        'api.users.update' => '更新用户',
        'api.users.destroy' => '删除用户',
        'api.users.getRoles' => '用户角色',
        'api.users.updateRoles' => '更新用户角色',
   // ],
    
    // 'api.roles'=>[
        'api.roles' => '角色',
        'api.roles.index' => '角色列表',
        'api.roles.create' => '创建角色',
        'api.roles.store' => '保存角色',
        'api.roles.show' => '显示角色',
        'api.roles.edit' => '编辑角色',
        'api.roles.update' => '更新角色',
        'api.roles.destroy' => '删除角色',
        'api.roles.ability' => '角色权限',
    //],
    
    // 'api.permission'=>[
        'api.permission' => '权限',
        'api.permission.index' => '权限列表',
        'api.permission.create' => '创建权限',
        'api.permission.store' => '保存权限',
        'api.permission.show' => '显示权限',
        'api.permission.edit' => '编辑权限',
        'api.permission.update' => '更新权限',
        'api.permission.destroy' => '删除权限',
        'api.permission.search' => '搜索权限',
    // ],
    
    // 'api.menu'=>[
        'api.menu' => '菜单',
        'api.menu.index' => '菜单列表',
        'api.menu.create' => '创建菜单',
        'api.menu.store' => '保存菜单',
        'api.menu.show' => '显示菜单',
        'api.menu.edit' => '编辑菜单',
        'api.menu.update' => '更新菜单',
        'api.menu.destroy' => '删除菜单',
        'api.menu.createButton' => '菜单按钮',
    // ],
    // 'api.upload'=>[
        'api.upload' => '上传',
        'api.upload.store' => '上传',
    // ],
    // 'api.company'=>[
        'api.company' => '公司',
        'api.company.index' => '公司列表',
        'api.company.create' => '创建公司',
        'api.company.store' => '保存公司',
        'api.company.show' => '显示公司',
        'api.company.edit' => '编辑公司',
        'api.company.update' => '更新公司',
        'api.company.destroy' => '删除公司',
        'api.company.search' => '搜索公司',
    // ],
    // 'api.devicetype'=>[
        'api.devicetype' => '设备分类',
        'api.devicetype.index' => '分类列表',
        'api.devicetype.create' => '创建分类',
        'api.devicetype.store' => '保存分类',
        'api.devicetype.show' => '显示分类',
        'api.devicetype.edit' => '编辑分类',
        'api.devicetype.update' => '更新分类',
        'api.devicetype.destroy' => '删除分类',
    // ],
    // 'api.deviceinfo'=>[
        'api.deviceinfo' => '设备信息',
        'api.deviceinfo.index' => '设备列表',
        'api.deviceinfo.create' => '创建设备',
        'api.deviceinfo.store' => '保存设备',
        'api.deviceinfo.show' => '显示设备',
        'api.deviceinfo.edit' => '编辑设备',
        'api.deviceinfo.update' => '更新设备',
        'api.deviceinfo.destroy' => '删除设备',
        'api.deviceinfo.devicetype' => '所有分类',
        'api.deviceinfo.area' => '区域设备',
    // ],
    // 'api.area'=>[
        'api.area' => '区域',
        'api.area.index' => '区域列表',
        'api.area.create' => '创建区域',
        'api.area.store' => '保存区域',
        'api.area.show' => '显示区域',
        'api.area.edit' => '编辑区域',
        'api.area.update' => '更新区域',
        'api.area.destroy' => '删除区域',
    // ],
    // 'api.data'=>[
        'api.data' => '数据',
        'api.data.index' => '数据列表',
    // ],
    // 'api.monitor'=>[
        'api.monitor' => '监控',
        'api.monitor.index' => '监控列表',
        'api.monitor.data' => '历史数据',
        'api.monitor.realdata' => '实时数据',
        'api.monitor.areadevice' => '区域设备',
    // ],
    // 'api.userlog'=>[
        'api.userlog' => '日志',
        'api.userlog.index' => '用户日志',
    // ],
    // 'api.control'=>[
        'api.control' => '控制',
        'api.control.update' => '更新',
        'api.control.device' => '设备',
        'api.control.devicedata' => '设备数据',
    // ],
    // 'api.warndefine'=>[
        'api.warndefine' => '告警定义',
        'api.warndefine.index' => '列表',
        'api.warndefine.create' => '创建',
        'api.warndefine.store' => '保存',
        'api.warndefine.show' => '显示',
        'api.warndefine.edit' => '编辑',
        'api.warndefine.update' => '更新',
        'api.warndefine.destroy' => '删除',
    // ],
    // 'api.warnnotify'=>[
        'api.warnnotify' => '告警配置',
        'api.warnnotify.index' => '列表',
        'api.warnnotify.create' => '创建',
        'api.warnnotify.store' => '保存',
        'api.warnnotify.show' => '显示',
        'api.warnnotify.edit' => '编辑',
        'api.warnnotify.update' => '更新',
        'api.warnnotify.destroy' => '删除',
    // ],
    // 'api.warnuser'=>[
        'api.warnuser' => '告警用户',
        'api.warnuser.index' => '列表',
        'api.warnuser.create' => '创建',
        'api.warnuser.store' => '保存',
        'api.warnuser.show' => '显示',
        'api.warnuser.edit' => '编辑',
        'api.warnuser.update' => '更新',
        'api.warnuser.destroy' => '删除',
        'api.warnuser.warnsetting'=>'通知方式',
    // ],
    // 'api.realwarn' => [
        'api.realwarn' => '实时告警',
        'api.realwarn.index' => '列表',
    // ],
    // 'api.report' => [
        'api.report' => '实时告警',
        'api.report.index' => '历史告警查询',
        'api.report.historysum' => '历史告警统计',
        'api.report.assetsum' => '设备资产统计',
    // ],
    // 'api.video' => [
        'api.video' => '视频',
        'api.video.index' => '视频中心',
    // ],
    // 'api.donghuang' => [
        'api.donghuang' => '动环',
        'api.donghuang.index' => '首页',
        'api.donghuang.device' => '设备',
        'api.donghuang.realdata' => '实时数据',
        'api.donghuang.storeDevice' => '添加设备',
    // ],
];

